version: "2.4"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
  